name: Delete obsolete branches
on:
  delete
env:
  DEST_REPO: microapps-test/workspace-microapps-test-bundles
  DEST_REPO_DIR: ../workspace-microapps-bundles-test
  BUNDLES_DIR: bundles
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v1

      - name: Checkout destination repository
        uses: actions/checkout@v1
        with:
          repository: ${{ env.DEST_REPO }}
          ref: master

      # GitHub Action unfortunately doesn't provide name of the deleted branch in the `delete` event. GITHUB_SHA and
      # GITHUB_REF variables refer to the default branch (master). Diff of all branches is used as a workaround.
      # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#delete-event-delete
      - name: Delete obsolete branches
        run: |
          git branch --remotes --format='%(refname:short)' | sed 's%^origin/%%' | sort | tee /tmp/branches_source.txt
          cd "${DEST_REPO_DIR}"
          git branch --remotes --format='%(refname:short)' | sed 's%^origin/%%' | sort | tee /tmp/branches_destination.txt

          comm -13 /tmp/branches_source.txt /tmp/branches_destination.txt | tee /tmp/branches_delete.txt

          "${GITHUB_WORKSPACE}/.github/scripts/git_setup.sh" "${DEST_REPO}" "${{ secrets.DEST_REPO_SSH_KEY }}"

          for branch in $(cat /tmp/branches_delete.txt)
          do
            git push origin --delete "${branch}"
          done
