name: Globalization
on:
  pull_request_target:
    branches:
      - master
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: G11n Radar
        uses: citrix-workspace/g11n-scan@v20.12.8
        with:
          repoToken: ${{secrets.GITHUB_TOKEN}}
          skip: 'bundles/coming_soon/'
      - name: Slack Notification        
        if: ${{ failure() }}        
        uses: archive/github-actions-slack@master        
        with:          
          slack-bot-user-oauth-access-token: ${{ secrets.SLACKBOT_TOKEN }}        
          slack-channel: g11n-scanner-microapps         
          slack-text: Globalization scan failed due to g11n issues have been found, refer to <https://github.com/${{ github.repository }}/actions| github actions> for more details.
