name: Validate pull request
on:
  pull_request
env:
  BUNDLES_DIR: bundles
  BUNDLES_DIST_DIR: bundles-dist
  BUNDLES_ARCHIVE_DIR: archives
  LINK_BUNDLES: https://github.com/microapps-test/workspace-microapps-test-bundles/tree/master/bundles/
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v1

      - name: Maven modules cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build bundlegen
        run: mvn --batch-mode clean package

      - name: Execute bundlegen
        run: |
          rm -rf "${BUNDLES_DIST_DIR}"

          main_class="com.citrix.microapps.bundlegen.BundlegenMain"
          args="${BUNDLES_DIR} ${BUNDLES_DIST_DIR} ${LINK_BUNDLES}"

          mvn --batch-mode exec:java -pl bundlegen -Dexec.mainClass="${main_class}" -Dexec.args="${args}"

      - name: Change bundle extensions zip to mapp
        run: |
          for f in ${BUNDLES_DIST_DIR}/${BUNDLES_ARCHIVE_DIR}/*/*.zip; do
              mv -- "$f" "${f%.zip}.mapp"
          done

      - name: Determine bundle artifacts path
        run: echo "BUNDLE_ARTIFACTS_PATH=${BUNDLES_DIST_DIR}/${BUNDLES_ARCHIVE_DIR}/*/*.mapp" >> $GITHUB_ENV

      - name: Upload bundle artifacts
        uses: actions/upload-artifact@v2
        with:
          name: bundles
          path: ${{ env.BUNDLE_ARTIFACTS_PATH }}
